CREATE TABLE IF NOT EXISTS coc (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  hall INT(2) NOT NULL,
  data LONGTEXT NOT NULL,
  avatar VARCHAR(1024) DEFAULT NULL,
  photos LONGTEXT DEFAULT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS coc_orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  coc_id INT UNSIGNED NOT NULL,
  paypal_order_id VARCHAR(128) NOT NULL UNIQUE,
  status VARCHAR(40) NOT NULL DEFAULT 'CREATED',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  payer_email VARCHAR(255) DEFAULT NULL,
  paypal_payload JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_coc_orders_coc_id (coc_id),
  CONSTRAINT fk_coc_orders_coc FOREIGN KEY (coc_id) REFERENCES coc(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
